version: "2.8"

http:
  address: 0.0.0.0:80
  pool:
    num_workers: 4
    max_jobs: 10000
    supervisor:
      exec_ttl: 300s

server:
  command: "php ./vendor/bin/roadrunner-worker"

  env:
  - APP_BASE_PATH: "./"
  - LARAVEL_OCTANE: "1"

rpc:
  listen: tcp://0.0.0.0:6001

logs:
  mode: production
  level: warn
  output: stdout
  encoding: json

service:
  supervisord:
    command: "./start_master.sh"
    process_num: 1
    exec_timeout: 0
    remain_after_exit: true
    restart_sec: 5
