apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tts-${PROJECT_NAME}-master
    service: ${PROJECT_NAME}-master
    version: "${PROJECT_APP_VERSION}"
    service_framework: laravel
    is_master_node: "true"
  annotations:
    docker_tag: "${DOCKER_TAG}"
  name: ${PROJECT_NAME}-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tts-${PROJECT_NAME}-master
  template:
    metadata:
      labels:
        app: tts-${PROJECT_NAME}-master
        service: ${PROJECT_NAME}-master
        version: "${PROJECT_APP_VERSION}"
        is_master_node: "true"
    spec:
      containers:
        - image: ${CI_REGISTRY_IMAGE}:${DOCKER_TAG}
          name: ${PROJECT_NAME}-master
          env:
            - name: CLUSTER_IS_MASTER
              value: "yes"
          envFrom:
          - configMapRef:
              name: ${PROJECT_NAME}
          ports:
          - name: http-api
            containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
              httpHeaders:
              - name: Content-Type
                value: application/json
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: ${MEM_MIN}
              cpu: ${CPU_MIN}
            limits:
              memory: ${MEM_MAX_MASTER}
              cpu: ${CPU_MAX_MASTER}
      restartPolicy: Always
      imagePullSecrets:
        - name: tts
        - name: ecr

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tts-${PROJECT_NAME}
    service: ${PROJECT_NAME}
  name: ${PROJECT_NAME}
spec:
  selector:
    service: ${PROJECT_NAME}
  ports:
  - name: http-${PROJECT_NAME}
    port: 80
    targetPort: http-api
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: api-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "api.thitruongsi.svc"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ${PROJECT_NAME}-services
spec:
  hosts:
  - "api.thitruongsi.svc"
  gateways:
  - api-gateway
  http:
  - match:
    - uri:
        prefix: /${PROJECT_NAME}-master/
    rewrite:
      uri: /
    route:
    - destination:
        host: ${PROJECT_NAME}
        port:
          number: 80