apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tts-${PROJECT_NAME}-master
    service: ${PROJECT_NAME}-master
    version: "${PROJECT_APP_VERSION}"
    service_framework: nodejs
  annotations:
    docker_tag: "${DOCKER_TAG}"
  name: ${PROJECT_NAME}-master
spec:
  selector:
    matchLabels:
      app: tts-${PROJECT_NAME}-master
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: tts-${PROJECT_NAME}-master
        service: ${PROJECT_NAME}-master
        version: "${PROJECT_APP_VERSION}"
        is_master_node: "true"
    spec:
      containers:
        - image: $CI_REGISTRY_IMAGE:$DOCKER_TAG
          name: ${PROJECT_NAME}-master
          env:
            - name: IS_MASTER
              value: "true"
            - name: CLUSTER_IS_MASTER
              value: "1"
            - name: TZ
              value: "Asia/Ho_Chi_Minh"
          envFrom:
          - configMapRef:
              name: ${PROJECT_NAME}
          ports:
          - name: http-api
            containerPort: 3000
          startupProbe:
            httpGet:
              path: /health
              port: 3000
              httpHeaders:
              - name: Content-Type
                value: application/json
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: 
                - "curl"
                - "--fail"
                - "-o"
                - "/dev/null"
                - "http://localhost:3000/health"
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
          resources:
            requests:
              memory: ${MEM_MIN}
              cpu: ${CPU_MIN}
            limits:
              memory: ${MEM_MAX}
              cpu: ${CPU_MAX}
      restartPolicy: Always
      imagePullSecrets:
        - name: tts
        - name: ecr
