apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tts-${PROJECT_NAME}
    service: ${PROJECT_NAME}
    version: "${PROJECT_APP_VERSION}"
  annotations:
    docker_tag: "${DOCKER_TAG}"
  name: ${PROJECT_NAME}
spec:
  selector:
    matchLabels:
      app: tts-${PROJECT_NAME}
  replicas: ${SCALE_MIN}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: tts-${PROJECT_NAME}
        service: ${PROJECT_NAME}
        version: "${PROJECT_APP_VERSION}"
    spec:
      containers:
        - image: $CI_REGISTRY_IMAGE:$DOCKER_TAG
          name: ${PROJECT_NAME}
          envFrom:
          - configMapRef:
              name: ${PROJECT_NAME}
          ports:
          - name: http-api
            containerPort: 3000
          readinessProbe:
            exec:
              command: 
                - "curl"
                - "-m"
                - "10"
                - "--fail"
                - "-o"
                - "/dev/null"
                - "http://localhost:3000/https://dropship.thitruongsi.com/robots.txt"
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command: 
                - "curl"
                - "-m"
                - "10"
                - "--fail"
                - "-o"
                - "/dev/null"
                - "http://localhost:3000/https://dropship.thitruongsi.com/robots.txt"
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          resources:
            requests:
              memory: ${MEM_MIN}
              cpu: ${CPU_MIN}
            limits:
              memory: ${MEM_MAX}
              cpu: ${CPU_MAX}
      restartPolicy: Always
      imagePullSecrets:
        - name: tts
        - name: ecr
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tts-${PROJECT_NAME}
    service: ${PROJECT_NAME}
  name: ${PROJECT_NAME}
spec:
  selector:
    service: ${PROJECT_NAME}
  ports:
  - name: http-${PROJECT_NAME}
    port: 3000
    targetPort: http-api
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: ${PROJECT_NAME}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${PROJECT_NAME}
  minReplicas: ${SCALE_MIN}
  maxReplicas: ${SCALE_MAX}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: api-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "api.thitruongsi.svc"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ${PROJECT_NAME}-services
spec:
  hosts:
  - "api.thitruongsi.svc"
  gateways:
  - api-gateway
  http:
  - match:
    - uri:
        prefix: /${PROJECT_NAME}/
    rewrite:
      uri: /
    route:
    - destination:
        host: ${PROJECT_NAME}
        port:
          number: 3000